### PR TITLE
LNK-2758 Add Iproducer to Listener

### PR DESCRIPTION
**Pull request by edward-miller-lcg**
## Summary by CodeRabbit

- **New Features**
	- Enhanced Kafka messaging capabilities for handling `ResourceNormalizedMessage` and `AuditEventMessage`.
	- Simplified producer management for better clarity and maintenance.

- **Bug Fixes**
	- Improved robustness in service initialization by enforcing non-null dependencies.

- **Refactor**
	- Streamlined dependencies by removing factory patterns in favor of direct producer instances.
	- Simplified resource handling within listeners and services, enhancing code maintainability.

### CODE REVIEW

**Review by arianamihailescu — APPROVED** [review]
Looks good

**Review by arianamihailescu — CHANGES_REQUESTED** [review]
The name 'kafkaProducer' does not exist in the current context

**Comment by edward-miller-lcg** [comment]
> The name 'kafkaProducer' does not exist in the current context

fixed

**Comment by edward-miller-lcg** [comment]
@arianamihailescu please re-review

**Review by arianamihailescu — APPROVED** [review]
Looks good

**Pull request merged**
