### PR TITLE
LNK-2753 Add IProducer to Tenant

### PR DESCRIPTION
**Pull request by edward-miller-lcg**
## Summary by CodeRabbit

- **New Features**
	- Streamlined Kafka producer initialization for better performance and clarity in the audit event creation process.
	- Integrated Kafka producer as a singleton service, enhancing message production capabilities across the application.

- **Bug Fixes**
	- Removed unnecessary abstractions around Kafka producer management, simplifying the code and potentially reducing errors.

- **Documentation**
	- Improved clarity in service registration logic to facilitate easier debugging and configuration management.

### CODE REVIEW

**Review by arianamihailescu — COMMENTED** [review]
Looks good, but I think you missed changing ReportScheduledJob to get the producer instead of the factory

**Review by arianamihailescu — CHANGES_REQUESTED** [review]
ReportScheduledJob should also be changed

**Comment by edward-miller-lcg** [comment]
> Looks good, but I think you missed changing ReportScheduledJob to get the producer instead of the factory

changed

**Review by arianamihailescu — APPROVED** [review]
Looks good

**Pull request merged**
